[package]
tool = "kryon"
name = "Pass"
entry = "src/app.zi"
module_roots = ["src", "."]
bridge_modules = ["app"]

[toolchain]
git = "https://github.com/ziranlang/ziran.git"
ref = "master"

[dependencies.kryon]
git = "https://github.com/kryonlabs/kryon.git"
ref = "master"

[install]
bin = "pass-gui"

[tool.kryon]
default_profile = "desktop"

[tool.kryon.profiles.desktop]
backend = "desktop"
host = "src/desktop.zi"

[tool.kryon.profiles.canvas]
backend = "canvas"

[dependencies.mingcute]
git = "https://github.com/kryonlabs/mingcute.git"
ref = "master"
